#pragma config(Sensor, in1,    conveyerAngle,  sensorPotentiometer)
#pragma config(Sensor, in2,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in3,    position,       sensorPotentiometer)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           rightConveyer, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           leftConveyer,  tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           conveyerElevator, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!


void moveConveyer(int angle){
	while(abs(SensorValue(conveyerAngle)-angle/4) > 20){
		if(SensorValue(conveyerAngle) < angle - 50)
			startMotor(conveyerElevator, 127);

		if(SensorValue(conveyerAngle) < angle)
			startMotor(conveyerElevator, 50);

		if(SensorValue(conveyerAngle) > angle + 50)
			startMotor(conveyerElevator, -80);

		if(SensorValue(conveyerAngle) > angle)
			startMotor(conveyerElevator, -15);
	}

}
//method to move conveyer to designated angle


void startConveyerUp(bool up){
	if(up){
		startMotor(leftConveyer,127);
		startMotor(rightConveyer,127);
	}
	else{
		startMotor(leftConveyer,-127);
		startMotor(rightConveyer,-127);
	}
}
//method to start conveyer belt
//if up, spool up, else spool down


void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}


task autonomous()
{

	int place = SensorValue(position)/1024;
	//produces value that tells robot its starting position
	//0 = blue, right
	//1 = blue, left
	//2 = red, right
	//3 = red, left


	//MIGHT WANT TO COLLECT CUBES FIRST Y'KNOW
	//...if that's okay with you...
	startMotor(rightMotor,63);
	startMotor(leftMotor,63);
	if(SensorValue(lineFollower)<000000){//FILL IN VALUES FOR LINE COLOR
		stopMotor(leftMotor);
		stopMotor(rightMotor);
	}
	//move forward (at half speed) until linefollower detects line


	if(place==0){

	}
	//aim for 9in goal
	//turn right; move far
	if(place==1){

	}
	//aim for 21in goal
	//turn left; move not far
	if(place==2){

	}
	//aim for 21in goal
	//turn right; move not far
	if(place==3){

	}
	//aim for 9 goal
	//turn left; move far

	//turn until on correct orientation
	//drive until goalpost
	//align conveyer elevation

	startConveyerUp(false);
	wait(5);
	//deposit cubes
	//????
	//win the game

}


task usercontrol()
{
	while (true)
	{


		arcadeControl(Ch2, Ch1, 5);
		//moving-the-robot stuff; don't know how it works

		if(SensorValue(vexRT(Btn6U) == 1)){
			startConveyerUp(true);
		}
		else if(SensorValue(vexRT(Btn6D) == 1)){
			startConveyerUp(false);
		}
		else{
			stopMotor(leftConveyer);
			stopMotor(rightConveyer);
		}
		//if holding right trigger up, move conveyer up
		//if holding right trigger down, move conveyer down
		//else, hold motors

		if(SensorValue(vexRT(Btn5U)==1)){
			startMotor(conveyerElevator, 127);
		}
		else if(SensorValue(vexRT(Btn5D)==1)){
			startMotor(conveyerElevator, -127);
		}
		else{
			stopMotor(conveyerElevator);
		}
		//if holding left up trigger, move conveyer up
		//if holding left down trigger, move conveyer down
		//else, hold position

		if(SensorValue(vexRT(Btn8U)==1)){
			moveConveyer(1);
		}
		if(SensorValue(vexRT(Btn8L)==1)){
			moveConveyer(1);
		}
		if(SensorValue(vexRT(Btn8R)==1)){
			moveConveyer(1);
		}
		if(SensorValue(vexRT(Btn8D)==1)){
			moveConveyer(1);
		}
		//8U moves conveyer to 21in goal
		//8L moves conveyer to 15in goal
		//8R moves conveyer to 9in goal
		//8D moves conveyer to 3in goal
		//VALUES ARE PLACEHOLDERS

	}
}
