#pragma config(Sensor, in1,    conveyerElevation, sensorPotentiometer)
#pragma config(Sensor, in2,    lineFollower,   sensorLineFollower)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           conveyerRight, tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port5,           conveyerLeft,  tmotorVex269_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           conveyerElevator, tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
	// Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	// .....................................................................................
	// Insert user code here.
	// .....................................................................................

	AutonomousCodePlaceholderForTesting();  // Remove this function call once you have "real" code.
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task usercontrol()
{
	// User control code here, inside the loop

	while (true)
	{
		// This is the main execution loop for the user control program. Each time through the loop
		// your program should update motor + servo values based on feedback from the joysticks.

		// .....................................................................................
		// Insert user code here. This is where you use the joystick values to update your motors, etc.
		// .....................................................................................


		arcadeControl(Ch2, Ch1, 5);
		//moving-the-robot stuff; don't know how it works

		if(SensorValue(vexRT(Btn6U) == 1)){
			startMotor(conveyerLeft, 127);
			startMotor(conveyerRight, 127);
		}
		else if(SensorValue(vexRT(Btn6D) == 1)){
			startMotor(conveyerLeft, -127);
			startMotor(conveyerRight, -127);
		}
		else {
			stopMotor(conveyerLeft);
			stopMotor(conveyerRight);
		}
		//if holding right trigger up, move conveyer in "positive" direction
		//if holding right trigger down, move conveyer in "negative" direction
		//else, hold motors

		if(SensorValue(vexRT(Btn5U) == 1){
			startMotor(conveyerElevator, 127);
		}
		else if(SensorValue(vexRT(Btn5D) == 1){
			startMotor(conveyerElevator, -127);
		}
		else{
			stopMotor(conveyerElevator);
		}
		//if holding left up trigger, move conveyer up
		//if holding left down trigger, move conveyer down
		//else, hold position


		//UserControlCodePlaceholderForTesting(); // Remove this function call once you have "real" code.
	}
}
